# Tokyo Night Dark theme for Tmux

# Entire status bar style
set -g status-style bg=colour235,fg=white

# Inactive window style
setw -g window-status-style bg=colour236
setw -g window-status-format " #[fg=colour240]#I #[fg=colour245]#W "

# Active window style
setw -g window-status-current-style bg=colour240
setw -g window-status-current-format " #[fg=colour250]#I #[fg=colour255,bold]#W "

# Pane borders (green for active window)
set -g pane-border-style fg=colour237
set -g pane-active-border-style fg=colour2

# Right side: time and session name
set -g status-right '#[fg=colour240]| #[fg=colour250]⧖ %H:%M #[fg=colour240]| #[fg=colour250]◆ #S #[default]'
