###################################################################
# General
###################################################################

# Start tabs at index 1 (tmux default is 0)
set -g base-index 1

# Make pane numbering consistent with windows (starting at 1 instead of 0)
setw -g pane-base-index 1

# Renumber windows when a window is closed
set -g renumber-windows on

# Automatically set window title
# set-window-option -g automatic-rename on
# set-option -g set-titles on

###################################################################
# Key-bindings
###################################################################

# Free the original `Ctrl-b` prefix keybinding.
unbind C-b

# Set prefix key to ctrl-a
# Not a problem for going to beginning because we're using zsh with vi mode.
set -g prefix C-a

# set -g default-terminal screen-256color
# set -g status-keys vi
# set -g history-limit 10000

# mouse? real hackers don't use a mouse
set-option -g mouse off

# vi keys for switching panes
# it also handles holding CTR and using hjkl to move between panes
# because otherwise you may accidentally block the move because you're
# still holding the prefix key when you press h, j, k, or l quickly
bind-key h select-pane -L
bind-key C-h select-pane -L
bind-key j select-pane -D
bind-key C-j select-pane -D
bind-key k select-pane -U
bind-key C-k select-pane -U
bind-key l select-pane -R
bind-key C-l select-pane -R

# Unbind the default split keys and rebind them to split with the same directory as the current pane.
unbind '"'
unbind %
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Splitting panes with more intuitive keys
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vi copypaste
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# shift-movement keys will resize panes
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

# No delay for escape key press
set -sg escape-time 0

###################################################################
# Colours and styling
###################################################################

# Refresh every 5 seconds
set -g status-interval 5

# Place status bar at the bottom
set -g status-position bottom

# Remove default session name from the left
set -g status-left ""

# Window separator
setw -g window-status-separator ""

# Source theme file (theme-active.conf is a symlink to theme-dark.conf or theme-light.conf)
source-file ~/.config/tmux/theme-active.conf
