# Catppuccin Latte (Light) theme for Alacritty

[colors.primary]
background = "#eff1f5"
foreground = "#4c4f69"

[colors.normal]
black   = "#5c5f77"
red     = "#d20f39"
green   = "#40a02b"
yellow  = "#df8e1d"
blue    = "#1e66f5"
magenta = "#8839ef"
cyan    = "#179299"
white   = "#acb0be"

[colors.bright]
black   = "#6c6f85"
red     = "#d20f39"
green   = "#40a02b"
yellow  = "#df8e1d"
blue    = "#1e66f5"
magenta = "#8839ef"
cyan    = "#179299"
white   = "#bcc0cc"
